# GitHub Actions workflow for running Playwright tests in CI/CD pipeline
name: Playwright CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install lsof and additional diagnostics
      - name: Install and check lsof
        run: |
          sudo apt-get update
          sudo apt-get install -y lsof || echo "lsof installation failed!"
          lsof || echo "lsof command failed!"
          # Check if lsof is installed
          if command -v lsof &> /dev/null
          then
              echo "lsof is successfully installed and found"
          else
              echo "lsof could not be found"
              exit 1
          fi

      # Step 4: Install dependencies for browsers (Chromium, Firefox, WebKit)
      - name: Install system dependencies for Playwright browsers
        run: |
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcups2 \
            libatk1.0-0 \
            libgtk-3-0 \
            libasound2 \
            libpangocairo-1.0-0 \
            libxshmfence1 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libdrm2 \
            libgbm1 \
            libxkbcommon0 \
            libflac8 \
            libmpg123-0 \
            libopengl0 \
            libxshmfence1 \
            libglu1-mesa \
            libgles2-mesa \
            # WebKit-specific dependencies
            libwoff1 \
            libopus0 \
            libharfbuzz-icu0 \
            libwebpdemux2 \
            libenchant1c2a \
            libhyphen0 \
            libgstreamer-gl1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-libav \
            libgstreamer-plugins-bad1.0-0 \
            libx264-155  # Additional media codecs

      # Step 5: Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 6: Run Playwright Tests
      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true
