name: Playwright CI/CD Pipeline

# Trigger on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build, Test, and Run Playwright
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use GitHub Secrets to store Docker Hub credentials
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t my-playwright-app .

      # Step 5: Run Playwright Tests
      - name: Run Playwright Tests
        run: docker run my-playwright-app npx playwright test

  # Job 2: Deploy to Docker Hub if tests pass
  deploy:
    needs: build_and_test  # Run this job only if tests pass
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Tag and push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag my-playwright-app ${{ secrets.DOCKER_USERNAME }}/my-playwright-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-playwright-app:latest
