# GitHub Actions workflow for running Playwright tests in CI/CD pipeline
name: Playwright CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # The CI job will run on the latest Ubuntu version

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify Node.js version

      # Step 5: Install required libraries for Playwright browsers
      - name: Install dependencies for browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcups2 \
            libatk1.0-0 \
            libgtk-3-0 \
            libasound2 \
            libpangocairo-1.0-0 \
            libxshmfence1 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libdrm2 \
            libgbm1 \
            libxkbcommon0 \
            libflac8 \
            libmpg123-0 \
            libopengl0 \
            libxshmfence1 \
            libglu1-mesa \
            libgles2-mesa

      # Step 6: Install Playwright dependencies and browsers
      - name: Install dependencies
        run: npm ci  # Clean install from package-lock.json

      # Step 7: Install Playwright Browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 8: Run Playwright Tests
      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true  # Signals that tests are running in CI

      # Optional: Upload Playwright report
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
